# Generated by Django 4.0.4 on 2022-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='img_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
