# Generated by Django 4.0.4 on 2022-05-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage_img_id_placeimage_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceImage',
            new_name='Image',
        ),
    ]
