# Generated by Django 4.0.4 on 2022-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_id',
            field=models.IntegerField(default=0),
        ),
    ]
